Extract serialization/deserialization code from iota.go repository.
iotaledger/hive.go pull request #281
Opened 2021-08-13 15:56 UTC by piotrm50

# Description of change

Add code responsible for serialization and de-serialization of structures that was previously located in `iota.go` repository, so that it can be used in other projects such as Goshimmer.
Now `iota.go` uses the code located in this repository. 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Ran unit tests locally. 

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-08-23 08:03 UTC, luca-moser requested changes

2021-09-08 06:44 UTC, piotrm50 commented on serializer/consts.go
> +	TokenSupply = 2_779_530_283_277_761
Moved back to `iota.go`

2021-09-08 06:44 UTC, piotrm50 commented on serializer/error.go
> +	ErrUnknownSignatureType = errors.New("unknown signature type")
Moved back to `iota.go`

2021-09-13 07:34 UTC, luca-moser approved these changes

2021-09-13 07:39 UTC, merged