Add unit tests: ads,  storable, memstorage, causalorder, accounts
iotaledger/hive.go pull request #514
Opened 2023-05-11 13:25 UTC by jkrvivian

# Description of change

Add unit tests to the following packages:
* ads
* storable
* memstorage
* causalorder
* accounts

2023-06-05 12:39 UTC, piotrm50 requested changes
Look at code coverage of and try to cover the missing scenarios.

2023-06-05 12:39 UTC, piotrm50 commented on ads/set_test.go
> +	newSet.Add(key)
Try adding the same element twice to make sure that it's handled correctly.

2023-06-05 12:39 UTC, piotrm50 commented on ads/set_test.go
> +	assert.Equal(t, 0, newSet.Size())
We should also test the `.Root()` method to make sure that it returns a correct value. Currently it's not covered by the tests at all.

2023-06-05 12:39 UTC, piotrm50 commented on ads/set_test.go
> +	err := newSet.Stream(func(key testKey) bool {
What happens if the callback returns `false`? Does it result in an error? Or an error can only occur inside of the underlying KVStore and cannot be induced by the user? If we can induce an error we should have a test that does this. 

Would anyway be nice to have a test with a callback that returns `false`.

2023-06-05 12:39 UTC, piotrm50 commented on ads/set_test.go
> +func TestStreamSet(t *testing.T) {
A side note for the `Stream` method implementation. Error handling is slightly confusing as the method uses a naked return and has two variables that can store errors from two separate sources, so maybe it's something that also should be fixed (not necessarily the scope of this PR though)

2023-06-05 12:39 UTC, piotrm50 commented on ads/map_test.go
> +	assert.False(t, newMap.Delete(key))
Test for getting a non-existent key is missing.
Test for setting the same key twice is missing (updating a value).
Test for `.Root` method is missing as we don't have coverage on this method at all. 
We should also test that the root changes after updating/deleting/adding elements - or maybe that should be tested by the underlying SMT's tests.

2023-06-05 12:39 UTC, piotrm50 commented on ads/map_test.go
> +	err := newMap.Stream(func(key testKey, value *testValue) bool {
Add a 3rd element that would cause returning `false` from the callback. It possibly should be another `Stream` call.

2023-06-05 12:39 UTC, piotrm50 commented on core/account/accounts_test.go
> +func TestAccount(t *testing.T) {
```suggestion
func TestAccounts(t *testing.T) {
```

2023-06-05 12:39 UTC, piotrm50 commented on core/account/accounts_test.go
> +			expectedGet: 0,
`expectedGet` is not used anywhere. Was it supposed to be `expectedTotalWeight`?

2023-06-05 12:39 UTC, piotrm50 commented on core/account/accounts_test.go
> +			weight:      10,
We should run tests with more accounts that have non-zero weight.

2023-06-05 12:39 UTC, piotrm50 commented on core/account/accounts_test.go
> +	for _, tc := range testCases {
`TotalWeight` is not tested.
`Root` is not tested. 
Updating account's weight is not tested. 

Another thing that I see in the constructor is that it's possible to pass a KVStore that is not empty and (presumably) the TotalWeight of the Accounts object needs to be initialized properly. Would be good to have that tested as well. 

`SelectAccounts` is also not touched by the tests. Would be good to have a simple test for that method.

Given the above, I'm not sure if that approach with iterating over `testCases` is flexible enough. 

Also, outside of the scope of this PR - `Accounts` don't have any way to delete accounts - is that by design?

2023-06-05 12:39 UTC, piotrm50 commented on core/account/selectedaccounts_test.go
> +	weight, exists := selectedAccounts.Get(account2)
`Get` a missing account is not tested. Also we should test an account that is part of the `members` set, but not part of the `accounts`. In this case the `Get` should return `0, true`.

2023-06-05 12:39 UTC, piotrm50 commented on core/account/selectedaccounts_test.go
> +	selectedAccounts.ForEach(func(id testID, weight int64) error {
Test `ForEach` with a callback that returns an error and make sure that the error is returned by the `ForEach` call.

2023-06-05 12:39 UTC, piotrm50 commented on core/causalorder/causalorder.go
> +	c.dagMutex.RLock(child.ID())
What is the reasoning behind updates to the locking? Was there a problem in the new parallel tests?

2023-06-05 12:39 UTC, piotrm50 commented on core/eventticker/eventticker_test.go
> +	require.False(t, has, "EventTicker.HasTicker() returned true, expected false")
try to `Get` a ticker from an evicted slot.
try to `Get` a ticker from a non-evicted slot that you never added tickers to.

2023-06-05 12:39 UTC, piotrm50 commented on core/eventticker/eventticker_test.go
> +	eventTicker.StartTicker(id)
Try to start ticker of an evicted slot and make sure that it was not started. 
Start the same ticker twice and check that the events are only trigerred once.

2023-06-05 12:39 UTC, piotrm50 commented on core/eventticker/eventticker_test.go
> +	eventTicker.EvictUntil(index(1))
Call evict until on already evicted slot index to make sure that it doens't have any weird side effects and that the following check in the implementation is covered . 

```
	if index <= r.lastEvictedIndex {
		return
	}
```

2023-06-05 12:39 UTC, piotrm50 commented on core/eventticker/eventticker_test.go
> +	eventTicker.StopTicker(id)
Stop ticker twice.
Stop ticker from an evicted slot.

2023-06-05 12:39 UTC, piotrm50 commented on core/eventticker/eventticker_test.go
> +	done := make(chan struct{})
Run the test a little longer to make sure that the function is actually executed multiple times at the correct time interval.

2023-06-06 09:27 UTC, jkrvivian commented on core/account/accounts_test.go
> +	for _, tc := range testCases {
I think we should have the `Delete`.

2023-06-12 12:24 UTC, piotrm50 approved these changes
Looks good!

2023-06-19 11:23 UTC, merged