Cleanup ds package (advancedset.AdvancedSet -> ds.Set)
iotaledger/hive.go pull request #527
Opened 2023-07-07 22:21 UTC by hmoog

TBC

2023-07-19 09:00 UTC, karimodm requested changes
Can you add test coverage for Apply (and setMutations) and Replace?

2023-07-19 09:00 UTC, karimodm commented on ds/set_impl.go
> +	return removedElements
Shouldn't this return the removedElements - removedElements.Intersect(elements)?

2023-07-19 09:00 UTC, karimodm commented on ds/set_impl.go
> +	*orderedmap.OrderedMap[T, types.Empty] `serix:"0"`
Would it be better to use a shrinkingmap here for the writeable counterpart as elements can be deleted?

2023-07-20 12:10 UTC, hmoog commented on ds/set_impl.go
> +	return removedElements
It should actually return the "previousValues" and no it should not intersect them as we need the full set to construct the mutations.

I renamed the return value to indicate that it returns all of the previousElements.

2023-07-20 12:11 UTC, hmoog commented on ds/set_impl.go
> +	*orderedmap.OrderedMap[T, types.Empty] `serix:"0"`
The OrderedMap brings Encode and Decode methods and uses a shrinking map internally, so for convenience and to not have to implement the methods manually I would keep it like it is.

2023-07-20 14:00 UTC, karimodm approved these changes

2023-07-20 14:00 UTC, merged